"""empty message

Revision ID: 077a7ac874e7
Revises: eb734a1619d1
Create Date: 2020-10-04 17:21:53.240263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077a7ac874e7'
down_revision = 'eb734a1619d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actor', type_='foreignkey')
    op.drop_column('actor', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('movie_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'actor', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###
