"""empty message

Revision ID: 11aa34d0de87
Revises: 
Create Date: 2020-10-06 19:56:04.911353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11aa34d0de87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actor_movie_id_fkey', 'actor', type_='foreignkey')
    op.drop_column('actor', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('actor_movie_id_fkey', 'actor', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###
